# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Build with Gradle Wrapper
      working-directory: java
      run: ./gradlew packageAll --scan --console=verbose
    - name: Archive Windows Release
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: java/build/package/windows/atlas-*.zip
    - name: Archive Linux Release
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          java/build/package/linux/atlas-*.tar.gz
          java/build/package/linux/atlas-*.deb
          java/build/package/linux/atlas-*.rpm
    - name: Archive Linux AppImage Release
      uses: actions/upload-artifact@v4
      with:
        name: linuxappimage
        path: java/build/package/linuxappimage/atlas.AppImage
    - name: Archive MacOS Release
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: java/build/package/macos/atlas-*.tar.gz
